#!/usr/bin/env python3
"""Turn results/engine_matrix*.csv into the markdown tables quoted in docs/VALIDATION_REPORT.md.

    python3 scripts/08_report_tables.py      ->  research/results/report_tables.md
"""
import os

import numpy as np
import pandas as pd

from engine_io import RESEARCH

R = os.path.join(RESEARCH, 'results')
net = pd.read_csv(os.path.join(R, 'engine_matrix.csv'))
gross = pd.read_csv(os.path.join(R, 'engine_matrix_gross.csv'))


def md(df, nd=3):
    """Minimal markdown table (no extra dependency)."""
    def f(v):
        return f'{v:.{nd}f}' if isinstance(v, (float, np.floating)) else str(v)
    head = '| ' + ' | '.join(map(str, df.columns)) + ' |\n|' + '|'.join(['---'] * len(df.columns)) + '|\n'
    return head + '\n'.join('| ' + ' | '.join(f(v) for v in row) + ' |' for row in df.itertuples(index=False)) + '\n'


def wavg(x, col, w='n'):
    return float((x[col] * x[w]).sum() / x[w].sum()) if x[w].sum() > 0 else np.nan


def cls(s):
    if s.startswith('BTC'): return 'crypto'
    if s.startswith('XAU'): return 'gold'
    if s.split('-')[0] in ('NAS100', 'US500', 'US30', 'DAX', 'FTSE', 'NQ'): return 'index'
    return 'fx'


def table(keys, title):
    rows = []
    for k, g in net.groupby(keys):
        gg = gross
        for kk, v in zip(keys if isinstance(keys, list) else [keys], k if isinstance(k, tuple) else (k,)):
            gg = gg[gg[kk] == v]
        d, o = g[g.period == 'dev'], g[g.period == 'oos']
        rows.append(dict(**{('/'.join(keys) if isinstance(keys, list) else keys): '/'.join(k) if isinstance(k, tuple) else k},
                         trades=int(g.n.sum()), win_rate=wavg(g, 'wr'), net_R_dev=wavg(d, 'avgR'), net_R_oos=wavg(o, 'avgR'),
                         net_R_all=wavg(g, 'avgR'), gross_R_all=wavg(gg, 'avgR'), cost_R=wavg(g, 'costR')))
    df = pd.DataFrame(rows)
    return f"### {title}\n\n" + md(df)


net['class'] = net.series.map(cls); gross['class'] = gross.series.map(cls)
out = ["# Report tables (generated by scripts/08_report_tables.py from results/engine_matrix*.csv)\n",
       "Net R = after spread and slippage; gross R = zero spread / zero slippage; cost R = mean spread / stop distance. "
       "dev / oos = development / hold-out halves defined per series in scripts/02_engine_matrix.py.\n",
       table(['series'], 'By series (all five setups pooled)'), table(['sleeve'], 'By setup (all series pooled)'),
       table(['class'], 'By market class')]
both = net.merge(gross[['series', 'sleeve', 'period', 'avgR']], on=['series', 'sleeve', 'period'], suffixes=('', '_gross'))
w = both[both.n >= 100].pivot_table(index=['series', 'sleeve'], columns='period', values=['avgR', 't', 'n'], aggfunc='first').dropna()
pos = w[(w[('avgR', 'dev')] > 0) & (w[('avgR', 'oos')] > 0)]
out.append(f"### Cells (series x setup, n >= 100 per half) positive in both halves\n\nnet of costs: {len(pos)} of {len(w)}\n")
gd = gross[gross.n >= 100]
g = gd.pivot_table(index=['series', 'sleeve'], columns='period', values=['avgR'], aggfunc='first').dropna()
p_dev = float((gd[gd.period == 'dev'].avgR > 0).mean()); p_oos = float((gd[gd.period == 'oos'].avgR > 0).mean())
out.append(f"before costs (gross): {int(((g[('avgR', 'dev')] > 0) & (g[('avgR', 'oos')] > 0)).sum())} of {len(g)} "
           f"(about {len(g) * p_dev * p_oos:.0f} expected if the two halves were independent coin flips at the observed positive rates {p_dev:.0%} / {p_oos:.0%})\n")
open(os.path.join(R, 'report_tables.md'), 'w').write("\n".join(out))
print("\n".join(out))
